app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'
urlpatterns=[
    path('bye/',bye,name='bye'),
]

project8/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
import app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('hai/',hai,name='hai'),
    path('hello/',hello,name='hello'),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def hai(request):
    return render(request,'hai.html')

def hello(request):
    return render(request,'hello.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def bye(request):
    return render(request,'bye.html')

templates/bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>This Bye Html Page</h1>
        <h2>We are using Specific urls to render this page</h2>
        <h6><a href="{% url 'hai' %}">Navigate to hai</a></h6>
        <h6><a href="{% url 'hello' %}">Navigate to Hello</a></h6>
    </center>
</body>
</html>

templates/hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Hai Html File</h1>
        <h6><a href="{% url 'hello' %}">Navigate to hello</a></h6>
        <h6><a href="{% url 'app2:bye' %}">Navigate to Bye</a></h6>
    </center>
</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Welcome to Hello Html File</h1>
        <h6><a href="{% url 'hai' %}">Navigate to Hai</a></h6>
        <h6><a href="{% url 'app2:bye' %}">Navigate To Bye</a></h6>
    </center>
</body>
</html>